### ISSUE TITLE
Parse Error when Installing on Kindle Fire HD8 2016 6th gen

### ISSUE THREAD

**Issue by perspector** [saber-notes/saber#1139]
### Before submitting an issue, please check the following

- [x] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Hello Saber developers,
I tried to install Saber v0.20.3 on my Kindle Fire HD8 2016 6th gen through multiple methods:
- apk from releases
- Google Play
- F-Droid
When trying to install the apk through the system installer, I get "Parse Error: Problem parsing package."

I tried again with SAI apk installer, and I get:
```
com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkLocalPath(DefaultApkSource.java:47)
	at com.aefyr.sai.model.apksource.FilterApkSource.getApkLocalPath(FilterApkSource.java:60)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:28)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(lambda)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

Saber installs fine on my Moto E.
I really love your app, and think it would be a great way to repurpose the Kindle.
Thank you so much!

### To reproduce

1. Download either FOSS or non-FOSS .apk file from v0.20.3 release
2. Try to install the apk on a Kindle.

### Expected behavior

Saber should install correctly via apk, Googke Play, or F-Droid aithout a parse error.

### Saber version

v0.20.3 F-Droid

### Device

Device: Kindle Fire HD 8 2016 6th gen
OS: Not sure, I think Amazon's OS is based on Android 8?

**Comment by perspector** [comment]
Also, when trying to update Saber from F-Droid, I get this error message:
![Screenshot_2024-03-04-17-18-04](https://github.com/saber-notes/saber/assets/52674257/95046746-6834-45d7-acfd-835a1395412b)

**Comment by perspector** [comment]
In addition, I just found out that this version of FireOS is based on Android 5.1 Lollypop. I think the codename of the device is giza and the model number is KFGIWI.

**Comment by adil192** [comment]
Saber currently requires Android 6 or newer
