### ISSUE TITLE
Images randomly getting replaced or emptied when adding more images

### ISSUE THREAD

**Issue by Nickno95** [saber-notes/saber#1159]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

In the iPad app, when adding images to a page, random existing images on other pages will be replaced with one of the newly added images while retaining original aspect ratio, or will be emptied out and become a transparent square. 

### To reproduce

Seems to occur randomly, but happens when there are images already in the document, and after you add multiple new images to a page. 

### Expected behavior

The existing images should not be getting replaced or emptied. 

### Saber version

0.20.3 App Store (20030)

### Device

iPadOS 17.4,
iPad Air 3

**Comment by QubaB** [comment]
Are there problems when "quickly" going to another page and adding an image on that page? Or it occurs during normal "slow work" on one page?

I haven't been able to replicate behavior described by you (ion Android), but it may be related to issue #1066. I created pull request #1128. May be it solve also your problem.

When you move to another page, images on not visible page are removed from memory. And if the note is saved (or autosaved) at the same moment, images can disappear (I observed this only on pdf background images) or can be reordered (I did not observed this). It is why I asked for "slow" of "quick" movement.

**Comment by Nickno95** [comment]
> Are there problems when "quickly" going to another page and adding an image on that page? Or it occurs during normal "slow work" on one page?
> 
> 
> 
> I haven't been able to replicate behavior described by you (ion Android), but it may be related to issue #1066. I created pull request #1128. May be it solve also your problem.
> 
> 
> 
> When you move to another page, images on not visible page are removed from memory. And if the note is saved (or autosaved) at the same moment, images can disappear (I observed this only on pdf background images) or can be reordered (I did not observed this). It is why I asked for "slow" of "quick" movement.

I tried messing with it and doing it quickly but could not get it to happen intentionally. 
I don't think I was doing it in a quick manner when it would happen. 
However I also ran into a bug where if I deleted a note with images, and created a new one and added images to it, it would show the images of the deleted one instead of what I added.

**Comment by QubaB** [comment]
> I tried messing with it and doing it quickly but could not get it to happen intentionally.
> I don't think I was doing it in a quick manner when it would happen.
So probably unrelated to #1066.

> However I also ran into a bug where if I deleted a note with images, and created a new one and added images to it, it would show the images of the deleted one instead of what I added.
Saber stores images in files "name of note".X  where X is number. All I can think of is that before Saber deleted the files from the deleted note, you managed to create a new one with the same name, so they didn't get deleted. I'm just speculating here.

**Comment by awwRoar** [comment]
Same issue. On an Android tablet. I added multiple images on to a page like a moodboard and moved on to the next page for some drawing. 

Pace of work - usual. 

When I came back, the images were all corrupt. Aspect ratios maintained but a single image replaced a few of them and the rest are now transparent. 

No idea what's happened or how the issue can be reproduced :/

**Comment by 4JX** [comment]
Commenting here since its related, though perhaps the background part may need to get its own issue. I've experienced this on multiple documents for both the background and image issues.

The background one is easy to reproduce, inserting the same image (same hash, regardless of filename) twice on a document starts removing the background image of whatever page the last addition landed on. This also happens with images with some groups of characters in the name, like `(`,`)`, and ` ` to name a few.

There's no loading circle on the pages either, so I assume it mistakenly deletes them in some way rather than it being a cache fetch issue like #1066.

As for the missing/resized *inserted* images I haven't found a reproducible setup, yet. But there's probably similar saving an retrieval issues on those.

Would love to do more testing on how exactly the files are being managed, but I'm currently unable to move my notes to external storage (there's more jank in the path handling there, permission issues aside), and there's no way to export them all either.

**Comment by QubaB** [comment]
What Saber version do you use @4JX

**Comment by 4JX** [comment]
`v0.25.5 (25050)` from Fdroid's repo, I can make a video of the background issue if you want.

**Comment by QubaB** [comment]
Please make short video. I will try on my tablet.

**Comment by 4JX** [comment]
This shows the background issue, where once I insert the logo again on another page the background clearing starts

https://github.com/user-attachments/assets/8b591793-1bcd-4660-b4f7-8b1c62688d1f

[PDF](https://sample-files.com/downloads/documents/pdf/sample-report.pdf), [Images](https://github.com/F0x1d/LogFox)

There's no Logcat errors that I could grab, I just see "failed to load PDF" errors in the APP's log

**Comment by QubaB** [comment]
I will look at it when I will have free time (hopely this week)

**Comment by QubaB** [comment]
I tried to look on this problem. Assets (images) are not very well managed in Saber (especially when one image is included more times.  My opinion is that it should be rewritten. I am not very experienced, it will take me long time to do such work. And at the end, as pull requests are not accepted by Adil, the work can be useless.

**Comment by 4JX** [comment]
My original plan was to try and fix it myself, but after seeing trivial fix PRs sitting stale for months I decided I'd rather try to get the attention of a mantainer by commenting on an issue. Don't worry too much about it.

**Comment by QubaB** [comment]
I am using my own version of Saber, because maintainer do not accept my pull requests. And because I do not use images too much, I am happy with current state of images.

**Comment by OmerRosler** [comment]
It still happens in version v.1.29.0, it usually happens when adding a new image in a page added in the middle (where there are other pictures after the one I added). The only affected images are the ones after the newly added one.
It seems to only happen where loading the document takes time (for large notes), and not when the document is small and loads fast.

**Comment by OmerRosler** [comment]
this bug is very problematic, because it means that practically, I can't edit a document with many images from fear I have to re-add all the images after every image change.

**Comment by cweiske** [comment]
I have this problem on Saber (v1.29.4 F-Droid) when adding a PDF via the "add image" button.
The PDF is gone, and with it the image I had added before I added the PDF.

When going back to the overview, the previous state is still visible (with the original image I added before the PDF)

`adb logcat` shows the following error:
```
5331 E FlutterJNI: Failed to decode image
5331 E FlutterJNI: android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.nCreate(Native Method)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:256)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1858)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1850)
5331 E FlutterJNI: 	at P1.a.d(SourceFile:1)
5331 E FlutterJNI: 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(SourceFile:17)
5296 I flutter : SEVERE: ErrorLogger: Exception: Invalid image data
5331 E FlutterJNI: Failed to decode image
5331 E FlutterJNI: android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.nCreate(Native Method)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:256)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1858)
5331 E FlutterJNI: 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1850)
5331 E FlutterJNI: 	at P1.a.d(SourceFile:1)
5331 E FlutterJNI: 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(SourceFile:17)
5296 I flutter : SEVERE: ErrorLogger: Exception: Invalid image data
```

The saber logs show:
```
SEVERE at 2026-01-19 16:45:43.099311
Exception: Invalid image data
Exception: Invalid image data
#0      _futurize (dart:ui/painting.dart:8035)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:7829)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2558)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:147)
#4      MemoryImage._loadAsync (package:flutter/src/painting/image_provider.dart:1719)
<asynchronous suspension>
#5      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1021)
<asynchronous suspension>


SEVERE at 2026-01-19 16:46:14.882331
Failed to load file: type 'Null' is not a subtype of type 'int'
type 'Null' is not a subtype of type 'int'
```

Steps to reproduce:
1. Open new note
2. Write/draw something
3. Click "add image", select jpg, tap on page to put the image there. Image is shown.
4. Click "add image", select pdf, tap on page to put the image there.
5. Handle circles are shown on the top left of the page, as if the image is 0x0px large.
6. Tap on page to get rid of the selection circles
7. Go back to overview to leave note
8. Re-open note
9. All images and all text are gone

**Comment by QubaB** [comment]
You cannot add pdf as image. It is shown in directory listing on Android (for androis is pdf an image, but for Saber not), but cannot be used as image. Pdf can be put only to background.

**Comment by cweiske** [comment]
> You cannot add pdf as image. It is shown in directory listing on Android (for androis is pdf an image, but for Saber not), but cannot be used as image. Pdf can be put only to background.

Great that you know that, but how should someone else know? My son is using Saber to take notes in school, and he scanned/photographed a hand out with [FairScan](https://github.com/pynicolas/FairScan/) and added it to Saber via the only way he knew - the image button.

I think Saber should either don't list pdf files when an image shall be selected, or - if that is not possible - check if it's a pdf file and reject it with an error message.

**Comment by QubaB** [comment]
On Android, programmer cannot choose what types of images will be shown in file selection. And pdf is unfortunately between image extensions so it is displayed.

There should be at least notice when you choose pdf, that it cannot be imported as image in Saber.
