### ISSUE TITLE
MissingPlatformDirectoryException on Arch from clean build

### ISSUE THREAD

**Issue by fybx** [saber-notes/saber#1333]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

If you are getting `Unhandled Exception: MissingPlatformDirectoryException(Unable to get application documents directory)` error after installing Saber from the AUR package [here](https://aur.archlinux.org/packages/saber) it may be fixed after installing [xdg-user-dirs](https://archlinux.org/packages/extra/x86_64/xdg-user-dirs/).

The full error message is as follows:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPlatformDirectoryException(Unable to get application documents directory)
#0      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:123)
<asynchronous suspension>
#1      FileManager.getDefaultDocumentsDirectory (package:saber/data/file_manager/file_manager.dart:59)
<asynchronous suspension>
#2      FileManager.getDocumentsDirectory (package:saber/data/file_manager/file_manager.dart:56)
<asynchronous suspension>
#3      FileManager.init (package:saber/data/file_manager/file_manager.dart:50)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#5      main (package:saber/main_common.dart:76)
<asynchronous suspension>
#6      main (package:saber/main.dart:31)
<asynchronous suspension>
```

**Comment by fybx** [comment]
this is a future reference for anyone who happens to have the same issue as I had, cheers!
