### ISSUE TITLE
Does not open notes created on another device: Permission denied

### ISSUE THREAD

**Issue by miguelmenendez** [saber-notes/saber#1403]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Android 14, Saber v0.24.2 F-Droid (25020).

When I create a note, for example, on the tablet and copy it to another device, for example, the mobile (copied by hand or synced with Syncthing), it does not show up on the device on which it **was not** created.

The same thing happens with the whiteboard. On the device on which it **was not** created, the error is:

_[SEVERE] PathAccessException: Cannot open file, path = '/storage/emulated/0/Documents/Saber/_whiteboard.sbn2' (OS Error: Permission denied, errno = 13)_

### To reproduce

Create a note on one device, copy it to another device, and try opening it on the second device.

### Expected behavior

Notes should open on any device regardless of which one they were created on.

### Saber version

0.24.2 F-Droid (25020)

### Device

- OS: Android 14

**Comment by ComputerElite** [comment]
Experiencing similar behavior. I uninstalled saber (installed via FDroid) then installed the Play store version and I couldn't even see the notes which are in my saber folder anymore. Then I switched back to the FDroid version. Trying to rename a folder doesn't work as well.

**Log:**
SEVERE at 2024-11-22 13:43:08.807425
PathAccessException: Rename failed, path = '/storage/emulated/0/Download/saber/Physik/MSS12' (OS Error: Operation not permitted, errno = 1)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195)
<asynchronous suspension>
#2      FileManager.renameDirectory (package:saber/data/file_manager/file_manager.dart:439)
<asynchronous suspension>
#3      _BrowsePageState.build.<anonymous closure> (package:saber/pages/home/browse.dart:153)
<asynchronous suspension>
#4      _GridFolderState.build.<anonymous closure> (package:saber/components/home/grid_folders.dart:210)
<asynchronous suspension>
#5      _RenameFolderDialogState.build.<anonymous closure> (package:saber/components/home/rename_folder_button.dart:109)
<asynchronous suspension>


SEVERE at 2024-11-22 13:43:09.396
PathAccessException: Rename failed, path = '/storage/emulated/0/Download/saber/Physik/MSS12' (OS Error: Operation not permitted, errno = 1)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195)
<asynchronous suspension>
#2      FileManager.renameDirectory (package:saber/data/file_manager/file_manager.dart:439)
<asynchronous suspension>
#3      _BrowsePageState.build.<anonymous closure> (package:saber/pages/home/browse.dart:153)
<asynchronous suspension>
#4      _GridFolderState.build.<anonymous closure> (package:saber/components/home/grid_folders.dart:210)
<asynchronous suspension>
#5      _RenameFolderDialogState.build.<anonymous closure> (package:saber/components/home/rename_folder_button.dart:109)
<asynchronous suspension>


SEVERE at 2024-11-22 13:43:09.578493
PathAccessException: Rename failed, path = '/storage/emulated/0/Download/saber/Physik/MSS12' (OS Error: Operation not permitted, errno = 1)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195)
<asynchronous suspension>
#2      FileManager.renameDirectory (package:saber/data/file_manager/file_manager.dart:439)
<asynchronous suspension>
#3      _BrowsePageState.build.<anonymous closure> (package:saber/pages/home/browse.dart:153)
<asynchronous suspension>
#4      _GridFolderState.build.<anonymous closure> (package:saber/components/home/grid_folders.dart:210)
<asynchronous suspension>
#5      _RenameFolderDialogState.build.<anonymous closure> (package:saber/components/home/rename_folder_button.dart:109)
<asynchronous suspension>


SEVERE at 2024-11-22 13:43:09.738086
PathAccessException: Rename failed, path = '/storage/emulated/0/Download/saber/Physik/MSS12' (OS Error: Operation not permitted, errno = 1)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195)
<asynchronous suspension>
#2      FileManager.renameDirectory (package:saber/data/file_manager/file_manager.dart:439)
<asynchronous suspension>
#3      _BrowsePageState.build.<anonymous closure> (package:saber/pages/home/browse.dart:153)
<asynchronous suspension>
#4      _GridFolderState.build.<anonymous closure> (package:saber/components/home/grid_folders.dart:210)
<asynchronous suspension>
#5      _RenameFolderDialogState.build.<anonymous closure> (package:saber/components/home/rename_folder_button.dart:109)
<asynchronous suspension>


SEVERE at 2024-11-22 13:43:09.891595
PathAccessException: Rename failed, path = '/storage/emulated/0/Download/saber/Physik/MSS12' (OS Error: Operation not permitted, errno = 1)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195)
<asynchronous suspension>
#2      FileManager.renameDirectory (package:saber/data/file_manager/file_manager.dart:439)
<asynchronous suspension>
#3      _BrowsePageState.build.<anonymous closure> (package:saber/pages/home/browse.dart:153)
<asynchronous suspension>
#4      _GridFolderState.build.<anonymous closure> (package:saber/components/home/grid_folders.dart:210)
<asynchronous suspension>
#5      _RenameFolderDialogState.build.<anonymous closure> (package:saber/components/home/rename_folder_button.dart:109)
<asynchronous suspension>

**Comment by QubaB** [comment]
Problem is on Android. It keeps owner which created file (owner app). Another app does not have access to other app files.

**Comment by QubaB** [comment]
Try to import note.

**Comment by TillF** [comment]
Importing the note does not fully help, as it seems to create a new copy (instead of using the existing file) and hangs on saving the file, if multipage notes are involved.

Is this probably related to the permissions issues discussed in #1223?
